# Generated by Django 3.2.15 on 2024-03-22 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название участка')),
                ('category_a', models.PositiveSmallIntegerField(verbose_name='A')),
                ('category_b', models.PositiveSmallIntegerField(verbose_name='B')),
                ('category_c1', models.PositiveSmallIntegerField(verbose_name='C1')),
                ('category_c2', models.PositiveSmallIntegerField(verbose_name='C2')),
                ('year_estimation', models.DateField()),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'OPI',
                'verbose_name_plural': 'OPI',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер Лицензии')),
                ('registration', models.DateField(verbose_name='Дата регистрации')),
                ('end_date', models.DateField(verbose_name='Срок окончания')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
            },
        ),
        migrations.CreateModel(
            name='OKATO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'OKATO',
                'verbose_name_plural': 'OKATO',
            },
        ),
        migrations.CreateModel(
            name='OPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'OPI',
                'verbose_name_plural': 'OPI',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название пользователя')),
                ('address', models.CharField(max_length=50, verbose_name='Юр. адрес')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('number', models.CharField(max_length=8, verbose_name='номер')),
            ],
            options={
                'verbose_name': 'Недропользователь',
                'verbose_name_plural': 'Недропользователи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Сoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('long', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.UniqueConstraint(fields=('name', 'address'), name='unique_name_address'),
        ),
        migrations.AddField(
            model_name='license',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arealicense', to='deposits.area', verbose_name='Участок'),
        ),
        migrations.AddField(
            model_name='license',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposits.owner', verbose_name='Недропользоваетль'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='okato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposits.okato'),
        ),
        migrations.AddField(
            model_name='area',
            name='coordinates',
            field=models.ManyToManyField(to='deposits.Сoordinates'),
        ),
        migrations.AddField(
            model_name='area',
            name='deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposits.deposit'),
        ),
        migrations.AddField(
            model_name='area',
            name='opi',
            field=models.ManyToManyField(to='deposits.OPI'),
        ),
        migrations.AddField(
            model_name='area',
            name='owners',
            field=models.ManyToManyField(through='deposits.License', to='deposits.Owner'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.UniqueConstraint(fields=('owner', 'area'), name='unique_owner_area'),
        ),
    ]
