# Generated by Django 3.2.15 on 2024-05-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name': 'Месторождение', 'verbose_name_plural': 'Месторождения'},
        ),
        migrations.AlterField(
            model_name='area',
            name='coordinates',
            field=models.ManyToManyField(related_name='area', to='deposits.Сoordinates'),
        ),
    ]
